# Generated by Django 4.1.3 on 2022-11-09 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='NichoMercado',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'nicho_mercado',
                    models.CharField(
                        max_length=30, verbose_name='nicho de mercado'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'nome',
                    models.CharField(max_length=30, verbose_name='tecnologia'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'logo',
                    models.ImageField(
                        blank=True, null=True, upload_to='logo_empresa'
                    ),
                ),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('cidade', models.CharField(max_length=30)),
                (
                    'endereco',
                    models.CharField(max_length=60, verbose_name='endereço'),
                ),
                (
                    'caracteristicas',
                    models.TextField(verbose_name='características'),
                ),
                (
                    'nicho_mercado',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='empresa.nichomercado',
                        verbose_name='nicho de mercado',
                    ),
                ),
                (
                    'tecnologias',
                    models.ManyToManyField(to='empresa.tecnologia'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Emprego',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'titulo',
                    models.CharField(max_length=30, verbose_name='título'),
                ),
                (
                    'level_experiencia',
                    models.CharField(
                        choices=[
                            ('E', 'Estágio'),
                            ('J', 'Júnior'),
                            ('P', 'Pleno'),
                            ('S', 'Sênior'),
                        ],
                        max_length=2,
                        verbose_name='nível de experiência',
                    ),
                ),
                ('data_final', models.DateField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('I', 'Interesse'),
                            ('C', 'Currículo enviado'),
                            ('E', 'Entrevista'),
                            ('D', 'Desafio técnico'),
                            ('F', 'Finalizado'),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    'empresa',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='empresa.empresa',
                    ),
                ),
                (
                    'tecnologias_dominadas',
                    models.ManyToManyField(to='empresa.tecnologia'),
                ),
                (
                    'tecnologias_estudar',
                    models.ManyToManyField(
                        related_name='study',
                        to='empresa.tecnologia',
                        verbose_name='tecnologias a estudar',
                    ),
                ),
            ],
        ),
    ]
