# Generated by Django 4.1.3 on 2022-11-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emprego',
        ),
    ]
