# Generated by Django 4.1.3 on 2022-11-10 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0002_delete_emprego'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprego',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'titulo',
                    models.CharField(max_length=30, verbose_name='título'),
                ),
                (
                    'level_experiencia',
                    models.CharField(
                        choices=[
                            ('E', 'Estágio'),
                            ('J', 'Júnior'),
                            ('P', 'Pleno'),
                            ('S', 'Sênior'),
                        ],
                        max_length=2,
                        verbose_name='nível de experiência',
                    ),
                ),
                ('data_final', models.DateField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('I', 'Interesse'),
                            ('C', 'Currículo enviado'),
                            ('E', 'Entrevista'),
                            ('D', 'Desafio técnico'),
                            ('F', 'Finalizado'),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    'empresa',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='empresa.empresa',
                    ),
                ),
                (
                    'tecnologias_dominadas',
                    models.ManyToManyField(to='empresa.tecnologia'),
                ),
                (
                    'tecnologias_estudar',
                    models.ManyToManyField(
                        related_name='study',
                        to='empresa.tecnologia',
                        verbose_name='tecnologias a estudar',
                    ),
                ),
            ],
        ),
    ]
