# Generated by Django 4.1.3 on 2022-11-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprego', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprego',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
