# Generated by Django 4.1.3 on 2022-11-11 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprego', '0002_emprego_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('titulo', models.CharField(max_length=30)),
                (
                    'prioridade',
                    models.CharField(
                        choices=[
                            ('B', 'baixa'),
                            ('A', 'alta'),
                            ('U', 'urgente'),
                        ],
                        max_length=1,
                    ),
                ),
                ('data', models.DateTimeField()),
                ('realizada', models.BooleanField(default=False)),
                (
                    'emprego',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='emprego.emprego',
                    ),
                ),
            ],
        ),
    ]
